### Directories
# Docker container working directory.
raw_data_dir: "../.test/data"
output_dir: "results"
clean_reads_dir: "results/01_clean_reads"
fastqc_reports_dir: "results/02_fastqc_reports"
kallisto_quant_dir: "results/03_kallisto_quant"        
multiqc_reports_dir: "results/04_multiqc_reports"
results_dir: "results/05_results"

references_dir: "references"

samplesheet: ../.test/config/samplesheet.csv
comparison: ../.test/config/comparison.csv




### Reference Files
# Docker container working directory.
ref_dir: "/refs"
transcriptome_index: "/refs/transcriptome.idx"


### Tools
# Choose the analysis method based on replicate availability:
# - Use "DESeq2" if replicates are available.
# - Use "edgeR" if no replicates are available.
method: "edgeR"

### Threads
# Number of CPU threads to use for processing.
threads: 16